name: iOS Continuous Delivery

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Import code signing certificate
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.P12_FILE_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
        provisioning-profile-base64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}

    - name: Resolve Swift packages
      run: xcodebuild -resolvePackageDependencies -project HomeWork.xcodeproj -scheme HomeWork

    - name: Build app
      run: xcodebuild -project HomeWork.xcodeproj -scheme HomeWork -sdk iphoneos -destination 'generic/platform=iOS' -configuration AppStoreDistribution archive -archivePath $PWD/build/HomeWork.xcarchive DEVELOPMENT_TEAM=VVLVJ8XG6Q -allowProvisioningUpdates

    - name: Export .ipa file
      run: xcodebuild -exportArchive -archivePath $PWD/build/HomeWork.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build

    - name: Upload to TestFlight
      env:
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      run: |
        xcrun altool --upload-app --type ios --file $PWD/build/HomeWork.ipa --apiKey $APP_STORE_CONNECT_API_KEY_ID --apiIssuer $APP_STORE_CONNECT_API_KEY_ISSUER_ID --apiKeyPath $APP_STORE_CONNECT_API_KEY
